name: Update Discord Events

# Run on schedule + manual trigger
on:
  workflow_dispatch: # allows manual trigger
  push:
    branches:
      - main
  schedule:
   - cron: '0,30 * * * *'

jobs:
  update-events:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Set environment variables
      - name: Set Discord secrets
        run: |
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> $GITHUB_ENV
          echo "GUILD_ID=${{ secrets.GUILD_ID }}" >> $GITHUB_ENV

      # Step 5: Run script
      - name: Run event fetch script
        run: node ./fetchDiscordEvents.js
